name: tests

on: [push, pull_request]

jobs:
  cargo_tests:
    name: ${{ matrix.channel }} ${{ matrix.target.toolchain }}
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target: [
          { "os": "linux-latest",   "toolchain": "x86_64-unknown-linux-gnu" },
          { "os": "linux-latest",   "toolchain": "x86_64-unknown-linux-musl" },
          { "os": "macOS-latest",   "toolchain": "x86_64-apple-darwin" },
          { "os": "windows-latest", "toolchain": "x86_64-pc-windows-msvc" },
          { "os": "windows-latest", "toolchain": "x86_64-pc-windows-gnu" }
        ]
        channel: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ format('{0}-{1}', matrix.channel, matrix.target.toolchain) }}
        profile: minimal
        override: true
    - run: cargo test
